project:
  type: website
  output-dir: docs

website:
  title: "R for Conservation Criminology and Wildlife Security "
  site-url: https://nvdoormaal.github.io/daikoro-blog/
  description: "This is a series of blog posts on how to build your own interactive reports for wildlife practioners"
  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: About me
        href: about.qmd
      - icon: github
        href: "https://github.com/nvdoormaal"
      - icon: linkedin
        href: "https://www.linkedin.com/in/nick-van-doormaal-9213a7a2/?locale=en_US"

format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

